PrintMartic_DashBoard/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Completion;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PrintMartic_DashBoard.Helper;
using PrintMartic_DashBoard.Helper.ViewModels;
using PrintMatic.Core;
using PrintMatic.Core.Entities;
using PrintMatic.Core.Entities.Identity;
using PrintMatic.Core.Repository.Contract;
using PrintMatic.Repository;
using System.Data;
using System.Drawing;
using System.Security.Claims;
using System.Text.Json;

namespace PrintMartic_DashBoard.Controllers
{
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IProdduct _prodduct;
        private readonly IMapper _mapper;
        private readonly UserManager<AppUser> _userManager;
        private readonly IProductColor _color;
        private readonly IProductSize _size;
        private readonly IWebHostEnvironment _environment;
        private readonly IProductPhoto _photo;

        public ProductController(IUnitOfWork unitOfWork,IProdduct prodduct, IMapper mapper,
             UserManager<AppUser> userManager,
            IProductColor color,
            IProductSize size , IWebHostEnvironment webHostEnvironment,IProductPhoto photo)
        {
            _unitOfWork = unitOfWork;
            _prodduct = prodduct;
            _mapper = mapper;
            _userManager = userManager;
            _color = color;
            _size = size;
            _environment = webHostEnvironment;
            _photo = photo;
        }



        //Get All Products    Get
        [Authorize(AuthenticationSchemes = "Cookies", Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var List = await _prodduct.GetAllProducts();

            return View(List);
        }

        [Authorize(AuthenticationSchemes = "Cookies", Roles = "Admin")]
        public async Task<IActionResult> WaitingProducts()
        {
            var List = await _prodduct.GetWaitingProducts();
            return View(List);
        }

        [Authorize(AuthenticationSchemes = "Cookies", Roles = "بائع,Admin")]
        public async Task<IActionResult> YourProducts()
        {
            try
            {
                var user = User.Identity.Name;
                var product = await _prodduct.GetYourProducts(user);
                return View(nameof(Index), product);
            }
            catch (Exception ex)
            {
                ViewData["Message"] = ex.InnerException?.Message.ToString() ?? ex.Message.ToString();
                return View("Error");
            }
        }

        [Authorize(AuthenticationSchemes = "Cookies", Roles = "Admin")]
        public async Task<IActionResult> InActiveProducts()
        {

            try
            {
                var product = await _prodduct.GetInActiveProducts();
                return View(nameof(Index), product);
            }
            catch (Exception ex)
            {
                ViewData["Message"] = ex.InnerException?.Message.ToString() ?? ex.Message.ToString();
                return View("Error");
            }
        }

        [Authorize(AuthenticationSchemes = "Cookies", Roles = "Admin")]
        public async Task<IActionResult> RestoreData(int id)
        {
            var item = await _unitOfWork.Repository<Product>().GetByIdAsync(id);
            item.IsDeleted = false;
            item.IsActive = true;
            item.Enter = true;
            var ListofProColor = await _color.GetIdOfProAsync(item.Id);
            foreach (var color in ListofProColor)
            {
                color.IsDeleted = false;
                color.IsActive = true;
                _unitOfWork.Repository<ProductColor>().Update(color);
                await _unitOfWork.Complet();
            }
            var ListofProSize = await _size.GetIdOfProAsync(item.Id);
            foreach (var size in ListofProSize)
            {
                size.IsDeleted = false;
                size.IsActive = true;
                _unitOfWork.Repository<ProductSize>().Update(size);
                await _unitOfWork.Complet();
            }
            _unitOfWork.Repository<Product>().Update(item);
            await _unitOfWork.Complet();
            return RedirectToAction(nameof(InActiveProducts));
        }
        [Authorize(AuthenticationSchemes = "Cookies", Roles = "Admin")]
        public async Task<IActionResult> Confirm(int id)
        {
            try
            {
                var item = await _unitOfWork.Repository<Product>().GetByIdAsync(id);
                item.Enter = true;
                _unitOfWork.Repository<Product>().Update(item);
                var count = await _unitOfWork.Complet();
                var Photos = await _photo.GetPhotosOfProduct(item.Id);
                foreach (var photo in Photos)
                {
                    photo.Enter = true;
                    _photo.Update(photo);
                    await _unitOfWork.Complet();
                }
                if (count > 0)
                {
                    ViewData["Message"] = "تم التأكيد";
                }
                else
                    ViewData["Message"] = "فشلت العمليه";
            }
            catch (Exception ex)
            {
                ViewData["Message"] = ex.InnerException?.Message.ToString() ?? ex.Message.ToString();
            }
            return RedirectToAction(nameof(WaitingProducts));

        }

        public async Task<IActionResult> Details(int id)
        {
            var item = await _prodduct.GetIDProducts(id);
            if (item == null)
            {
                TempData["Message"] = "لم يتم العثور على هذا العنصر";
                return RedirectToAction(nameof(Index));
            }
            var itemMapped = _mapper.Map<Product, ProductVM>(item);
            if (item.ProductColors.Any())
            {
                itemMapped.Colors = item.ProductColors.ToList();
            }
            if (item.ProductSizes.Any())
            {
                itemMapped.Sizes = item.ProductSizes.ToList();
            }

            if (item.ProductPhotos.Any())
            {
                foreach (var photo in item.ProductPhotos)
                {
                    itemMapped.photos.Add(photo.Photo);
                }
            }
            return View(itemMapped);
        }

        [Authorize(AuthenticationSchemes = "Cookies", Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            try
            {
                ProductVM ProductVM = new ProductVM();
                var List = await _unitOfWork.Repository<Category>().GetAllAsync();
                ProductVM.Categories = List;
                List<AppUser> users = new List<AppUser>();
                foreach (var item in _userManager.Users)
                {
                    if (item.IsCompany == true)
                    {
                        users.Add(item);
                    }
                }
                ProductVM.Users = users;

                return View(ProductVM);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.InnerException?.Message.ToString() ?? ex.Message.ToString());
                ;
                return RedirectToAction(nameof(Index));
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(AuthenticationSchemes = "Cookies", Roles = ("Admin"))]
        public async Task<IActionResult> Create(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                   
                    if (productVM.NormalPrice <= 500)
                    {
                        productVM.TotalPrice = productVM.NormalPrice * 1.7m;
                    }
                    else
                    {
                        productVM.TotalPrice = productVM.NormalPrice * 2m;
                    }
                    productVM.UrgentPrice = productVM.TotalPrice * 2m;
                   productVM.Enter = true;
                    var itemMapped = _mapper.Map<ProductVM, Product>(productVM);
                   _unitOfWork.Repository<Product>().Add(itemMapped);
                    var count = await _unitOfWork.Complet();
                    if (productVM.PhotoFiles.Any())
                    {
                        foreach (var file in productVM.PhotoFiles)
                        {
                            ProductPhotos productPhotos = new ProductPhotos();
                            productPhotos.Photo = file.FileName;
                            productPhotos.Photo = DocumentSetting.UploadFile(file, "products");
                            productPhotos.ProductId = itemMapped.Id;
                            productPhotos.FilePath = Path.Combine(_environment.ContentRootPath, "wwwroot\\Uploads\\products", productPhotos.Photo);
                            productPhotos.Enter = true;
                            _photo.Add(productPhotos);
                            _photo.Complet();
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("PhotoFiles", "ادخل صور هذا المنتج");
                    }
                    if (productVM.ColorJson != null)
                        {
                            var colors = JsonConvert.DeserializeObject<List<string>>(productVM.ColorJson);
                            if (colors.Count > 0)
                            {
                                foreach (var hexCode in colors)
                                {

                                    ProductColor productColor = new ProductColor()
                                    {

PrintMartic_DashBoard/Controllers/ReviewController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrintMartic_DashBoard.Helper.ViewModels;
using PrintMatic.Core;
using PrintMatic.Core.Entities;
using PrintMatic.Core.Repository.Contract;

namespace PrintMartic_DashBoard.Controllers
{
    
    public class ReviewController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IReviewRepository _review;

        public ReviewController(IUnitOfWork unitOfWork,IMapper mapper,IReviewRepository review )
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _review = review;
        }
        public async Task<IActionResult> Index()
        {
            var List =await _review.GetAllIncludeProductAsync();

            return View(List);
        }

        public async Task<IActionResult> Details(int id)
        {
            var item = await _review.GetIdIncludeProductAsync(id);
            if (item == null) return NotFound();
            var RevMapped = _mapper.Map<Review,ReviewVM>(item);
            return View(RevMapped);
        }

        public async Task<IActionResult> Delete(int id)
        {
            return await Details(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id , ReviewVM reviewVM)
        {
            try
            {
                var RevMapped = _mapper.Map<ReviewVM,Review>(reviewVM);
                RevMapped.IsDeleted = true;
                RevMapped.IsActive = false;
                _unitOfWork.Repository<Review>().Update(RevMapped);
                var count = await _unitOfWork.Complet();

                if (count> 0)
            {
                TempData["Message"] = "تم إضافة حذف التعليق بنجاح";
            }
            return RedirectToAction(nameof(Index));

            }
            catch 
            {
                TempData["Message"] = "فشلت عملية الحذف ";
                return View(reviewVM);
            }
        }
    }
}

PrintMartic_DashBoard/Controllers/SaleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrintMartic_DashBoard.Helper.ViewModels;
using PrintMatic.Core;
using PrintMatic.Core.Entities;

namespace PrintMartic_DashBoard.Controllers
{
    [Authorize(AuthenticationSchemes = "Cookies", Roles = "بائع,Admin")]
    public class SaleController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public SaleController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        //Get 
        public async Task<IActionResult> Index()
        {
            var List = await _unitOfWork.Repository<Sale>().GetAllAsync();
            return View(List);
        }

        //Get Details 
        public async Task<IActionResult> Details(int id)
        {
            var item = await _unitOfWork.Repository<Sale>().GetByIdAsync(id);
            if (item == null) return RedirectToAction("Index");
            return View(item);
        }

        //Open Form of Create
        public IActionResult Create()
        {
            return View();
        }

        //Create Sale --Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, SaleVM saleVM)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    if (saleVM.SaleEndDate< saleVM.SaleStartDate)
                    {
                        ModelState.AddModelError("SaleEndDate", "ادخل تاريخ انتهاء آخر");
                    }
                    else
                    {
                        var sale = _mapper.Map<SaleVM, Sale>(saleVM);

                        _unitOfWork.Repository<Sale>().Add(sale);
                        var count = await _unitOfWork.Complet();
                        if (count > 0)
                        {
                            TempData["Message"] = "تم إضافة تفاصيل الخصم بنجاح";
                        }
                        return RedirectToAction(nameof(Index));
                    }
                    
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.InnerException?.Message.ToString() ?? ex.Message.ToString());
                }
            }
            TempData["Message"] = "فشلت عملية الإضافه";
            return View(saleVM);
        }

        //Open Form of Edit --get
        public async Task<IActionResult> Edit(int id)
        {
            var item = await _unitOfWork.Repository<Sale>().GetByIdAsync(id);
            if (item == null) return RedirectToAction(nameof(Index));
            var Mapped = _mapper.Map<Sale , SaleVM>(item);
            return View(Mapped);
        }

        //Edit Sale -- post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SaleVM saleVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (saleVM.SaleEndDate < saleVM.SaleStartDate)
                    {
                        ModelState.AddModelError("SaleEndDate", "ادخل تاريخ انتهاء آخر");
                    }
                    else
                    {
                        var sale = _mapper.Map<SaleVM, Sale>(saleVM);

                        _unitOfWork.Repository<Sale>().Update(sale);
                        var count = await _unitOfWork.Complet();
                        if (count > 0)
                        {
                            TempData["Message"] = "تم تعديل تفاصيل الخصم بنجاح";
                        }
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.InnerException?.Message.ToString() ?? ex.Message.ToString());
                }
            }
            TempData["Message"] = "فشلت عملية التعديل";
            return View(saleVM);
        }

        //Open form of delete --get
        public async Task<IActionResult> Delete(int id)
        {
            return await Details(id);
        }

        //Delete Sale --post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Sale sale) 
        {
            try
            {
                sale.IsDeleted = true;
                sale.IsActive = false;
                _unitOfWork.Repository<Sale>().Update(sale);
                var count =await _unitOfWork.Complet();
                
                if (count > 0)
                {
                    TempData["Message"] = "تم حذف تفاصيل الخصم بنجاح";
                }
                return RedirectToAction(nameof(Index));

            }
            catch 
            {
                TempData["Message"] = "فشلت عملية الحذف";
                return View(sale);
            }
        }
    }
}

PrintMartic_DashBoard/Views/Shared/_FooterPartial.cshtml
 <footer class="footer mt-auto">
            <div class="copyright bg-white">
              <p>
                &copy; <span id="copy-year"></span> Copyright Mono Dashboard Bootstrap Template by <a class="text-primary" href="http://www.iamabdus.com/" target="_blank" >Abdus</a>.
              </p>
            </div>
            <script>
                var d = new Date();
                var year = d.getFullYear();
                document.getElementById("copy-year").innerHTML = year;
            </script>
          </footer>

PrintMartic_DashBoard/Views/Shared/_HeadPartial.cshtml
<nav class="topnav navbar navbar-light bg-white">
    <button type="button" class="navbar-toggler text-muted mt-2 p-0 mr-3 collapseSidebar">
        <i class="fe fe-menu navbar-toggler-icon"></i>
    </button>
    <form class=" bg-white w-25 form-inline mr-auto searchform text-muted">
        <input class="form-control mr-sm-2 bg-transparent border-0 pl-4 text-muted" type="search" placeholder="Type something..." aria-label="Search">
    </form>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link text-muted my-2" href="#" id="modeSwitcher" data-mode="light">
                <i class="fe fe-sun fe-16"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-muted my-2" href="./#" data-toggle="modal" data-target=".modal-shortcut">
                <span class="fe fe-grid fe-16"></span>
            </a>
        </li>
        <li class="nav-item nav-notif">
            <a class="nav-link text-muted my-2" href="./#" data-toggle="modal" data-target=".modal-notif">
                <span class="fe fe-bell fe-16"></span>
                <span class="dot dot-md bg-success"></span>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-muted pr-0" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="avatar avatar-sm mt-2">
                    <img src="~/assets/avatars/face-1.jpg" alt="..." class="avatar-img rounded-circle">
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Profile</a>
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activities</a>
            </div>
        </li>
    </ul>
</nav>

PrintMartic_DashBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrintMartic_DashBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrintMartic_DashBoard.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrintMartic_DashBoard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Sale</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Review" asp-action="Index">Review</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductPhoto" asp-action="Index">ProductPhoto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductSale" asp-action="Index">ProductSale</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PrintMartic_DashBoard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>