PrintMartic_DashBoard/Controllers/ProductSaleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrintMartic_DashBoard.Helper;
using PrintMartic_DashBoard.Helper.ViewModels;
using PrintMatic.Core;
using PrintMatic.Core.Entities;
using PrintMatic.Core.Repository.Contract;

namespace PrintMartic_DashBoard.Controllers
{
    [Authorize(AuthenticationSchemes = "Cookies", Roles = "بائع,Admin")]
    public class ProductSaleController : Controller
    {
        private readonly IProductSale _productSale;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IProdduct _prodduct;
        private readonly ISaleRepository _sale;

        public ProductSaleController(IProductSale productSale ,IMapper mapper,
            IUnitOfWork unitOfWork , IProdduct prodduct , ISaleRepository sale)
        {
            _productSale = productSale;
            _mapper = mapper;
            _unitOfWork = unitOfWork;
            _prodduct = prodduct;
            _sale = sale;
        }
        public async Task<IActionResult> Index()
        {
            var List = await _productSale.GetActiveSales();
            return View(List);
        }

        public async Task<IActionResult> Details(int ProductId , int SaleId)
        {
            var item = await _productSale.GetByIDAsync(ProductId,SaleId);
            if(item == null)
            {
                ViewData["Message"] = "لم يتم العثور على هذا العنصر";
                return RedirectToAction("Index");
            }
           var PSMapped = _mapper.Map<ProductSale , ProductSaleVM>(item);
            return View(PSMapped);
        }


        public async Task<IActionResult> Create()
        {
            var list = await _prodduct.GetAllProductswithouttables();
            var SaleList = await _sale.GetActiveSales();
         
            var PSMapped = new ProductSaleVM();
            PSMapped.Products = list;
            PSMapped.Sales = SaleList;
            return View(PSMapped);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductSaleVM productSaleVM)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    if(productSaleVM.ProductId == 0 || productSaleVM.SaleId == 0)
                    {
                        ModelState.AddModelError("PriceAfterSale", "اختر اسم المنتج ونسبة الخصم");
                    }else
                    {
                        var product = await _unitOfWork.Repository<Product>().GetByIdAsync(productSaleVM.ProductId);
                        var sale = await _unitOfWork.Repository<Sale>().GetByIdAsync(productSaleVM.SaleId);

                        var paS = _productSale.GetPrice(sale.SaleDiscountPercentage, product.TotalPrice);
                        productSaleVM.PriceAfterSale = paS;
                        var ProSale = _mapper.Map<ProductSaleVM, ProductSale>(productSaleVM);
                        _productSale.Add(ProSale);
                        var count = await _unitOfWork.Complet();
                        if (count > 0)
                        {
                            ViewData["Message"] = "تم إضافة الخصم على المنتج بنجاح";
                        }
                        return RedirectToAction(nameof(Index));
                    }

                }
                catch(Exception ex) 
                {
                    ModelState.AddModelError(string.Empty, ex.InnerException?.Message.ToString() ?? ex.Message.ToString());
               
                }

            }
            var list = await _prodduct.GetAllProductswithouttables();
            var SaleList = await _sale.GetActiveSales();
            productSaleVM.Sales = SaleList;
            productSaleVM.Products = list;
            TempData["Message"] = "فشلت عملية الإضافه";
            return View(productSaleVM);

        }


        public async Task<IActionResult> Edit(int ProductId , int SaleId)
        {
            var item = await _productSale.GetByIDAsync(ProductId, SaleId);
            if (item == null) {
                TempData["Message"] = "Not Found";
                return RedirectToAction(nameof(Index));
            }
            var itemMapped = _mapper.Map<ProductSale , ProductSaleVM>(item);
            var list = await _prodduct.GetAllProductswithouttables();
            var SaleList = await _sale.GetActiveSales();
            itemMapped.Products = list;
            itemMapped.Sales = SaleList;
            return View(itemMapped);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductSaleVM productSaleVM)
        {
            if (ModelState.IsValid) 
            {
                try
                {
                    if (productSaleVM.ProductId == 0 || productSaleVM.SaleId == 0)
                    {
                        ModelState.AddModelError("PriceAfterSale", "اختر اسم المنتج ونسبة الخصم");
                    }
                    else
                    {
                        var product = await _unitOfWork.Repository<Product>().GetByIdAsync(productSaleVM.ProductId);
                        var sale = await _unitOfWork.Repository<Sale>().GetByIdAsync(productSaleVM.SaleId);
                        var paS = _productSale.GetPrice(sale.SaleDiscountPercentage, product.TotalPrice); productSaleVM.PriceAfterSale = paS;
                        var ProSale = _mapper.Map<ProductSaleVM, ProductSale>(productSaleVM);
                        _productSale.Update(ProSale);
                        var count = await _unitOfWork.Complet();
                        if (count > 0)
                        {
                            ViewData["Message"] = "تم تعديل الخصم على المنتج بنجاح";
                        }
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.InnerException?.Message.ToString() ?? ex.Message.ToString());
                }

            }
            var list = await _prodduct.GetAllProductswithouttables();
            var SaleList = await _sale.GetActiveSales();
            productSaleVM.Products = list;
            productSaleVM.Sales = SaleList;
            TempData["Message"] = "فشلت عملية التعديل";
            return View(productSaleVM);

        }


        public async Task<IActionResult> Delete(int ProductId, int SaleId)
        {
            return await Details(ProductId, SaleId);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProductSaleVM productSaleVM) 
        {
            try
            {
                var ProSale = _mapper.Map<ProductSaleVM, ProductSale>(productSaleVM);
               
                _productSale.Delete(ProSale);
                var count = await _unitOfWork.Complet();
                if (count > 0)
                {
                    TempData["Message"] = "تم حذف الخصم على المنتج بنجاح";
                }
                return RedirectToAction(nameof(Index));

            }catch
            {
                TempData["Message"] = "فشلت عملية الحذف";
                return View(productSaleVM);
            }
        }

    }
}

PrintMartic_DashBoard/Views/ProductSale/Create.cshtml
@model ProductSaleVM

@{
    ViewData["Title"] = "Create";
}



    <div class="m-auto  bg-white p-5">
        <h1>إضافة خصم لمنتج </h1>
        @if (!string.IsNullOrEmpty(TempData["Message"] as string))
        {
            <div class="alert alert-primary mt-3 mb-2">
                @TempData["message"]
            </div>
        }
        <hr />
        <form asp-action="Create" method="post">


            <partial name="PartialViews/CreateEditView" />
            <div class="form-group mt-4">
                <input type="submit" value="إضافه" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-light">العوده</a>
            </div>
        </form>
    </div>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

PrintMartic_DashBoard/Views/ProductSale/Delete.cshtml
@model ProductSaleVM
@{
    ViewData["Title"] = "Delete";
}


    <div class="m-auto  bg-white p-5">
        <h1>إزالة الخصم لمنتج </h1>
        @if (!string.IsNullOrEmpty(TempData["Message"] as string))
        {
            <div class="alert alert-primary mt-3 mb-2">
                @TempData["message"]
            </div>
        }
        <hr />

        <form asp-action="Delete" method="post">


            <partial name="PartialViews/DeleteDetialsView" />

            <div class="form-group mt-4">
                <input type="submit" value="حذف" class="btn btn-danger " />
                <a asp-action="Index" class="btn btn-light">العوده</a>
            </div>
        </form>
    </div>



@* @section Scripts {
    <partial name="_ValidationScriptsPartial" />
} *@

PrintMartic_DashBoard/Views/ProductSale/Details.cshtml
@model ProductSaleVM
@{
    ViewData["Title"] = "Details";
}



<hr />


<div class="m-auto  bg-white p-5">
        <h1>تفاصيل الخصم </h1>
        <div>

            <partial name="PartialViews/DeleteDetialsView" />

            <div class=" mt-4">
                <a href="~/ProductSale/Edit?ProductId=@Model.ProductId&SaleId=@Model.SaleId" class="btn btn-primary">تعديل</a>

                <a asp-action="Index" class="btn btn-light">العوده</a>
            </div>
        </div>
 </div>

PrintMartic_DashBoard/Views/ProductSale/Edit.cshtml
@model ProductSaleVM
@{
    ViewData["Title"] = "Edit";
}



    <div class="m-auto  bg-white p-5">
        <h1>تعديل خصم للمنتج</h1>
        @if (!string.IsNullOrEmpty(TempData["Message"] as string))
        {
            <div class="alert alert-primary mt-3 mb-2">
                @TempData["message"]
            </div>
        }
        <hr />

        <form asp-action="Edit" method="post">


            <partial name="PartialViews/CreateEditView" />
            <div class="form-group mt-4">
                <input type="submit" value="حفظ" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-light">العوده</a>
            </div>
        </form>
    </div>


   

@* @section Scripts {
    <partial name="_ValidationScriptsPartial" />

} *@

PrintMartic_DashBoard/Views/ProductSale/Index.cshtml
@model IEnumerable<ProductSale>





        <div class="m-auto  bg-white p-5">
    <a class="btn btn-outline-secondary " style="float: left; width: 170px; " asp-controller="ProductSale" asp-action="Create">
        إضافة خصم جديد
    </a>
            <h1>جميع الخصومات على المنتجات </h1>
            @if (!string.IsNullOrEmpty(TempData["Message"] as string))
            {
                <div class="alert alert-primary mt-3 mb-2">
                    @TempData["message"]
                </div>
            }
            <hr />
           
                            <div class="card shadow">
                                <div class="card-body">
                                    <div class="toolbar">
                                        <form class="form">
                                            <div class="form-row">
                                                <div class="form-group col-auto mr-auto">
                                                    <label class="my-1 mr-2 sr-only" for="inlineFormCustomSelectPref1">Show</label>
                                                    @* <select class="custom-select mr-sm-2" id="inlineFormCustomSelectPref1">
                                                    <option value="">...</option>
                                                    <option value="1">12</option>
                                                    <option value="2" selected>32</option>
                                                    <option value="3">64</option>
                                                    <option value="3">128</option>
                                                    </select> *@
                                                </div>
                                                <div class="form-group col-auto">
                                                    <label for="search" class="sr-only">Search</label>
                                                    <input type="text" class="form-control" id="search1" value="" placeholder="Search">
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- table -->
                                    <table class="table table-borderless table-hover">
                                        <thead>
                                            <tr>
                                                <td>
                                                    <div class="custom-control custom-checkbox">
                                                        <input type="checkbox" class="custom-control-input" id="all2">
                                                        <label class="custom-control-label" for="all2"></label>
                                                    </div>
                                                </td>
                                                <th>اسم المنتج</th>
                                                <th>الخصم</th>
                                                <th>السعر بعد الخصم</th>
                                               
                                                <th>العمليات</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>

                                                @foreach (var item in Model)
                                                {
                                                <tr>


                            <td>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="all2">
                                    <label class="custom-control-label" for="all2"></label>
                                </div>
                            </td>
                                                    <td>
                                                            @Html.DisplayFor(modelItem => item.Product.Name)
                                                    </td>
                                                    <td>
                                                            @Html.DisplayFor(modelItem => item.Sale.SaleDiscountPercentage)
                                                    </td>
                                                    <td>
                                                            @Html.DisplayFor(modelItem => item.PriceAfterSale)
                                                    </td>
                                                  
                                                    <td>
                                                        <button class="btn btn-sm dropdown-toggle more-horizontal" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            <span class="text-muted sr-only">Action</span>
                                                        </button>
                                                        <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="~/ProductSale/Edit?ProductId=@item.ProductId&SaleId=@item.SaleId">تعديل</a>
                                    <a class="dropdown-item" href="~/ProductSale/Delete?ProductId=@item.ProductId&SaleId=@item.SaleId">حذف</a>
                                    <a class="dropdown-item" href="~/ProductSale/Details?ProductId=@item.ProductId&SaleId=@item.SaleId">تفاصيل</a>
                                                        </div>
                                                    </td>

                                                </tr>
                                                }



                                        </tbody>

                                    </table>
                                    @* <nav aria-label="Table Paging" class="mb-0 text-muted">
                                    <ul class="pagination justify-content-center mb-0">
                                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                                    </ul>
                                    </nav> *@
                                </div>
                            </div>
                        </div> <!-- customized table -->
                    </div> <!-- end section -->
                </div>

            </div>
        </div>
   